project:
  type: website

website:
  #title: "Data Governance & Information Security [BETA]"
  title: "Ultralearner / Systemic Advisor [BETA]"
  navbar:
    right:
      - insights.qmd
      - sectors.qmd
      - skills.qmd
      - publications.qmd
      - zine.qmd
      - contact.qmd
      - icon: mailbox
        href: mailto:pe@peterebenhoch.com
      - icon: linkedin
        href: https://linkedin.com/in/ebenhoch
  page-footer:
  #    background: light # or `dark`
      left: Â© Dr. Peter Ebenhoch 
      right: "2025"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    include-in-header:
      - text: |
          <script src="https://cdn.usefathom.com/script.js" data-site="KTGPPUFD" defer></script>


